name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: actix-gym-training
          POSTGRES_PASSWORD: changeit
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - name: Build
      run: cargo build --verbose

    - name: Migrate database
      run: |
        sudo apt-get install libpq-dev -y
        cargo install --version=0.2.0 sqlx-cli --no-default-features --features postgres
        sqlx database create
        sqlx migrate run

    #- name: Run tests
    #  run: cargo test --verbose
    
    # Cargo test 
    - name: Generate coverage file
      if: (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
      run: |
          which cargo-tarpaulin || cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml -- --skip=test_stream_timeout --skip=test_message_timeout --skip=test_restart_sync_actor
    
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.0.15
      with:
        file: cobertura.xml

   
    
    
    
      
      
